### ISSUE TITLE
Support multiple dexes (including Gen 7 support)

### ISSUE THREAD

**Issue by robinjoseph08** [pokedextracker/pokedextracker.com#178]
# Goals
- zero-downtime deployments of all changes
- be able to have several dexes that are independent of each other (generations, shiny, forms, etc)
- all existing links (i.e. `/u/username`) are still functional
- dexes are deep-linked for shareability

# Implementation

## Dexes to Support
none of these are mutually exclusive, so they need to be implemented as toggles as opposed to types.
- shiny
- gen 7 vs gen 6
- national vs. regional (?)
- later, this setup should be able to support
  - forms
  - genders
  - etc

### `pokemon`
| column | type | modifiers | notes |
| --- | --- | --- | --- |
| `generation` | integer | not null | generation that pokemon was first introduced |
| `sun_location` | string | - | eventual sun location |
| `moon_location` | string | - | eventual moon location |

### `dexes`
| column | type | modifiers | notes |
| --- | --- | --- | --- |
| `id` | serial | not null | primary key |
| `user_id` | string | not null | unique contraint with `slug` & `user_id` |
| `title` | string | not null | user provided title for each dex |
| `slug` | string | not null | generated slug from `title` |
| `shiny` | boolean | not null |  |
| `generation` | integer | not null |  |
| `date_created` | timestamp | not null |  |
| `date_modified` | timestamp | not null |  |

### `captures`
| column | type | modifiers | notes |
| --- | --- | --- | --- |
| `user_id` ➡️ `dex_id` |  |  |  |

### Order of Tasks
- [x] [1] create `dexes` table
- [x] [1] save default dex for every new user
- [x] [2] retroactively create a dex for each existing user
- [x] [3] add `dex_id` to `captures`
- [x] [3] save the `dex_id` for every new capture
- [x] [4] retroactively add all `dex_id`s for each existing capture
- [x] [4] change primary key from `[user_id, pokemon_id]` to `[dex_id, pokemon_id]`
- [x] [5] accept either user or dex for the capture endpoints
- [x] [6] switch frontend to use dex instead of user
- [x] [7] add support for gen 7
- [ ] [8] remove references to user

### Remaining Tasks
- [x] profile page (with refactoring)
- [x] add create, edit, and delete dex endpoints
- [x] create dex modal
- [x] edit dex modal (including delete & confirm delete)
- [x] update sign up page to include first dex properties
- [x] update nav bar
- [x] add shiny indicator
- [x] add gen 7 shiny sprites to pokesprite
- [x] add dismiss-able notification about changes that links to blog post
- [x] update homepage
- [x] setup blogggg
- [x] theme blog
- [ ] deploy front-end
  - [ ] update ashketchum10 account
  - [x] update alolan evolutions
- [x] publish blog post
- [ ] post reddit post and tweets

## Other
- `/u/username` will now point to a profile page (one time breaking change)
- each individual dex then will have a description and a unique url based on that description (`/u/username/cool-living-dex`)
  - editing the description of a dex will change the URL and old links will not be redirected
  - show a warning for this on edit
- each dex should have a way to edit settings
- on signup, users should be able to pick the settings for their first dex
- there should be a quick nav to switch between dexes from the tracker page
