### ISSUE TITLE
Gen 7 National Dex

### ISSUE THREAD

**Issue by mrpsyduck** [pokedextracker/pokedextracker.com#235]
Although getting a complete National Dex in Gen 7 is still not quite legal, with Pokémon Bank right around the corner, I would recommend allowing users to create Gen 7 living dexes with the National Dex.

**Comment by ami** [comment]
definitely! we've planned to do this [since we released the feature](https://pokedextracker.com/blog/sun-moon-support-and-more/) and will support this as soon as pokebank is released.

**Comment by SimenB** [comment]
It's been released now

**Comment by robinjoseph08** [comment]
@SimenB yup, we're gonna hopefully get this out this weekend! we also noticed that you put up some PRs, and we'll be sure to get to them once we get this update out! 😄

**Comment by robinjoseph08** [comment]
# Goals

- zero-downtime deployments of all changes
- allow support for a gen 7 national dex including alolan forms
- continue to support editing to and from any other kind of dex

# Implementation

## Backend

- [ ] allow `national` when creating/editing a dex for gen 7 but not gen 6
- [ ] migration
  - add nullable `form`, `order`, `box`, `id` to `pokemon`
  - populate `id` with auto-incrementing int
  - change all foreign keys to look at `pokemon.id`
  - change primary key from `national_id` to `id`
- [ ] change _most_ lookups form `national_id` to `id`
- [ ] once ready, add alolan forms to `pokemon` and `evolutions` (making sure that nothing breaks)
- [ ] migrate captures to alolan forms if gen 7 dex (making sure nothing breaks)

## Frontend

- [ ] update register form
- [ ] update create form
- [ ] update edit form (w/ warnings)
- [ ] make sure that the region filter is correct
- [ ] add regional/national label
- [ ] update box filtering to use `box` and `order`
- [ ] change all uses of `national_id` with `id`
- [ ] use `form` for sprites

**Comment by Certerazvi** [comment]
Can't wait for this! ^^

**Comment by Certerazvi** [comment]
Any idea when it's going to be released? :D

**Comment by robinjoseph08** [comment]
@Certerazvi just deployed it! Sorry for the delay!
