### ISSUE TITLE
Ultra Sun + Ultra Moon Support

### ISSUE THREAD

**Issue by ami** [pokedextracker/pokedextracker.com#282]
based on [this poll](https://twitter.com/PokedexTracker/status/932101769739452416) and long-term considerations, we've decided to split things by game instead of by generation.

- `region` => `game_family`
- `generation` => `game`

**do not doubt this**

### To Do

- [x] [api] create a `game_families` table
  - `id` (e.g. `red_blue`, `yellow`, `gold_silver`, `crystal`, `ruby_sapphire`, etc)
  - `name`
  - `generation` (not sure it'll be needed long-term, but might help in the migration to be able to join on this table)
  - `regional_total` - total number of regional pokemon that will be used for the progress bar
  - `national_total` - total number of pokemon that will be used for the progress bar
  - `order`
  - `published` (possibly to denote which games we support currently)
- [x] [api] create a `games` table
  - `id` (e.g. `red`, `blue`, `yellow`, `gold`, `silver`, `crystal`, `ruby`, `sapphire`, etc)
  - `name`
  - `game_family_id`
  - `order`
- [x] [api] create games list endpoint
- [x] [api] deploy
- [x] [api] manually populate the `games` and `game_families` table with each one
- [x] [api] add `game_family_id` column to `pokemon`
  - text
  - backfill based on `generation` (pick the first game family it was in; well probs have to figure out discrepancies afterwards)
  - make non-nullable afterwards
  - add to pokemon serialization
- [x] [api] create `game_family_dex_numbers` table to better accommodate regional data
  - backfill based on existing region ids on the pokemon table
  - make kalos just increment through the different regions (i.e. central, coastal, mountain)
  - serialize it as properties in pokemon
- [x] [api] add `game_id` (integer) and `regional` (boolean) columns to `dexes`
  - make both nullable for now
  - add both to dex serialization
- [x] [api] update the dex create, dex update, and user create endpoints to save `game_id` and `regional`
  - update joi validation for all endpoints, but make `game` and `regional` optional
  - based on `generation` if `game` is not passed in
  - based on `region` if `regional` is not passed in
  - if gen 6, just pick a game and go with it, probs omega ruby
- [x] [api] deploy
- [x] [api] manually adjust any discrepancies with the dex numbers
  - gs vs hgss
  - rs vs oras
  - bw vs b2w2
- [x] [api] manually adjust any discrepancies with game families on pokemon (no work needed since gen 7 is [the only one that introduced pokemon mid-gen](https://en.wikipedia.org/wiki/Pok%C3%A9mon_(video_game_series)#Seventh_generation_(2016%E2%80%93present)))
- [x] [api] backfill `dexes.game_id` and `dexes.regional`
  - same notes as above
  - make non-nullable afterwards
- [x] [api] remove not null from `dexes.generation` and `dexes.region`
- [x] [api] deploy
- [x] [api] dex `total` property can use `game.game_family.national_total`
- [x] [api] update capture filtering to use `game_families.order` instead of `generation`
  - `region` => `game_family`
  - `generation` => `game`
  - in capture controller
- [x] [api] add the ability to query pokemon (retrieve endpoint) by new stuff in addition to old stuff
  - `region` => `game_family`
  - `generation` => `game`
  - add it to the `evolutions` function on the pokemon model
  - update joi validation
- [x] [api] deploy
- [x] [frontend] update all logic surrounding `generation` and `region` to use `game` and `game_family` instead
- [x] [frontend] update internal requests to pass in `game` and `regional` for all forms mentioned above
- [x] [frontend] deploy
- [x] [api] add `us_location` and `um_location` to `pokemon`
- [x] [api] deploy
- [x] [api] populate `us_location`/`um_location`
- [x] [api] insert rows into `game_family_dex_numbers` for usum
- [x] [api] add new pokemon to database
- [x] [api] deploy to refresh cached pokemon
- [x] [frontend] update spritesheet
- [x] [frontend] update all forms to account for changes
  - allow to pick game, not a generation
  - use the `/games` endpoint to fetch all published games and info about them
- [x] [frontend] replace generation label with game label
- [x] [frontend] replace all instances of `generation`
  - replace generation label with game label
  - key off `game` and `regional` in the info locations component
  - key off game family in the info component
- [x] [frontend] nuke region filter
  - nuke `regionCheck`
  - nuke `region` from global state and any `mapStateToProps`
  - grep for `region`
- [x] [blog] make bitly of eventual blog post url
- [x] [frontend] add notification with bitly blog post url
- [x] [blog] write blog post
  - apologize for the delay
  - mention the refactor to support game vs generation
  - mention how future game releases are going to be much faster now
  - potentially mention the removal of the region filter and the future
  - maybe mention donations and where the money will go, perks, etc
- [x] [blog] make screenshot of flair for post
- [ ] [blog] publish blog post
- [x] [frontend] finish and merge donations PR
- [ ] [frontend] deploy
- [ ] [other] update ashketchum10's dexes

### Clean Up

- [ ] [api] drop columns
  - `pokemon.generation`
  - `pokemon.{region}_id`
  - `dexes.generation`
  - `dexes.region`
- [ ] [api] remove all joi validation for unused params
  - dex create
  - dex update
  - pokemon retrieve
  - user create
- [ ] [api] make locations use `games` instead of being columns on `pokemon`
- [ ] [frontend] cleanup `showGameWarning` logic
- [ ] [frontend] cleanup location info logic
