### ISSUE TITLE
Manage infrastructure better with Terraform

### ISSUE THREAD

**Issue by robinjoseph08** [pokedextracker/pokedextracker.com#294]
itll be easier to keep track of and make changes to if its done through infrastructure-as-code. the [infrastructure repo](https://github.com/pokedextracker/infrastructure) is where this will be kept

- [x] s3 bucket for tfstate
- [x] iam user for travis to lint and validate
- [x] network (vpc, subnets, etc)
- [x] route53
- [x] cloudwatch billing alert
- [ ] kubernetes
