### ISSUE TITLE
Add support for Sword and Shield

### ISSUE THREAD

**Issue by robinjoseph08** [pokedextracker/pokedextracker.com#334]
**todo**:

- [x] add new `other` trigger for evolutions since there are some odd evolution methods in these games @robinjoseph08 
- [x] pull `box` out of pokemon and affiliate it with a type of dex (i.e. game/regional combo) @robinjoseph08 
- [x] deploy api @robinjoseph08 
- [x] add unpublished games/game family directly to the db @robinjoseph08
- [x] add new pokemon to db @robinjoseph08
- [x] add new dex numbers to db @robinjoseph08
- [x] add new evolutions to db @robinjoseph08
- [x] add locations to db @robinjoseph08
- [x] redeploy api (to refresh cache) @robinjoseph08
- [x] make edits to sprites, blocked on https://github.com/msikma/pokesprite/issues/54 @ami 
- [x] add new spritesheet and css @robinjoseph08
- [x] deploy frontend @robinjoseph08
- [x] write blog post @ami
- [x] create bitly link @ami
- [x] add notification @ami
- [x] update homepage @ami
- [ ] publish blog post @ami or @robinjoseph08
- [ ] update games/game family to be published @robinjoseph08
- [ ] deploy frontend @robinjoseph08
- [ ] update ashketchum01's dexes in prod @ami or @robinjoseph08
- [ ] tweet blog post @ami or @robinjoseph08 

**after release**:

- [ ] add shiny sprites for sword and shield
- [x] drop `pokemon.box` column
- [ ] add `serebii_slug` to `game_families`
- [ ] add game family to evolutions (think about the implementation for this)
